CREATE SCHEMA IF NOT EXISTS CI_STAGING;
CREATE SCHEMA IF NOT EXISTS CI_INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS CI_MARTS;

CREATE SCHEMA IF NOT EXISTS PROD_STAGING;
CREATE SCHEMA IF NOT EXISTS PROD_INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS PROD_MARTS;

CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.DEV_STAGING;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.DEV_INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.DEV_MARTS;